name = "pos-frontend-bangachieu2"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "pos-frontend-bangachieu2"

[env.production.vars]
VITE_API_URL = "https://pos-backend-bangachieu2.bangachieu2.workers.dev"
VITE_APP_NAME = "ComputerPOS Pro"
VITE_APP_VERSION = "1.0.0"
VITE_ENVIRONMENT = "production"

[env.preview]
name = "pos-system-bangachieu2-preview"

[env.preview.vars]
VITE_API_URL = "https://pos-backend-bangachieu2.bangachieu2.workers.dev"
VITE_APP_NAME = "ComputerPOS Pro (Preview)"
VITE_APP_VERSION = "1.0.0-preview"
VITE_ENVIRONMENT = "preview"
