name = "smartpos-web"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Force HTTPS redirect
[[redirects]]
from = "http://smartpos-web.pages.dev/*"
to = "https://smartpos-web.pages.dev/:splat"
status = 301
force = true

[env.production]
name = "smartpos-web"

# Environment variables for production
[env.production.vars]
VITE_API_BASE_URL = "https://smartpos-api-bangachieu2.bangachieu2.workers.dev/api/v1"
VITE_APP_ENV = "production"

# Security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Cache-Control = "public, max-age=0, must-revalidate"

# Cache headers for static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
