name = "smartpos-inventory-app"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

[env.production]
name = "smartpos-inventory-app"

[env.production.vars]
VITE_API_URL = "https://smartpos-api.bangachieu2.workers.dev"
VITE_APP_NAME = "SmartPOS - Quản Lý Kho"
VITE_APP_VERSION = "1.0.0"

[[pages_build_config]]
command = "npm install && npm run build"
destination_dir = "dist"
root_dir = "."

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
